name: CI Android

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: ./gradlew cAT
          api: 28
          tag: default
          abi: x86
          cmdOptions: -noaudio -no-boot-anim -no-window
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Updater-Screenshots
          if-no-files-found: error
          path: |
            app/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            app/build/outputs/androidTest-results/connected
      - name: Archive Espresso results
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: Updater-Espresso-report
          path: app/build/reports/androidTests/connected
